version: "3"

networks:
  backend:

volumes:
  pgdata:

services:
  web:
    restart: always
    # Dockerfile의 위치를 지정
    build: ./web 
    ports:
      - "8100:8000"
    depends_on:
      - postgres
    volumes:
      - ./web:/app
    networks:
      - backend
    env_file: .env
    command: './runserver.sh'

  postgres:
    restart: always
    image: postgres:10.1
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - backend
